server:
  port: 3355

spring:
  application:
    name: config-client-service
  cloud:
    config:
      uri: http://localhost:3344
      name: config
      label: master
      profile: dev

eureka:
  client:
    # 是否向注册中心注册自己
    register-with-eureka: true
    # 是否需要检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
  instance:
    instance-id: config-client-service-3355
    prefer-ip-address: true
    #心跳时间间隔
    lease-renewal-interval-in-seconds: 20
    #心跳时间等待时间
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: "*"

config:
  info: "dsadas"
